<?php

namespace ContainerSQSmBUC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Help\FileUploader' shared autowired service.
     *
     * @return \App\Help\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Help/FileUploader.php';

        return $container->privates['App\\Help\\FileUploader'] = new \App\Help\FileUploader();
    }
}
