<?php

namespace ContainerG8bXFbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZmJkqoKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zmJkqoK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmJkqoK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.zmJkqoK.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.zmJkqoK": it references class "App\\Entity\\Article" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'fileUploader' => ['privates', 'App\\Help\\FileUploader', NULL, 'Cannot autowire service "App\\Help\\FileUploader": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.'],
        ], [
            'article' => 'App\\Entity\\Article',
            'em' => '?',
            'fileUploader' => 'App\\Help\\FileUploader',
        ]);
    }
}
