<?php

namespace ContainerG8bXFbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Help\FileUploader' shared autowired service.
     *
     * @return \App\Help\FileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service "App\\Help\\FileUploader": argument "$targetDirectory" of method "__construct()" has no type-hint, you should configure its value explicitly.');
    }
}
